export const book = Object.freeze({
    ROOT:     '/',
    LESSON1:  '/lesson-1',
    LESSON2:  '/lesson-2',
    LESSON3:  '/lesson-3',
    LESSON4:  '/lesson-4',
    LESSON5:  '/lesson-5',
    LESSON6:  '/lesson-6',
    LESSON7:  '/lesson-7',
    LESSON8:  '/lesson-8',
    LESSON9:  '/lesson-9',
    LESSON10: '/lesson-10',
    LESSON11: '/lesson-11',
    LESSON12: '/lesson-12',
    LESSON13: '/lesson-13',
    LESSON14: '/lesson-14',
    LESSON15: '/lesson-15',
});
